global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wis2node-monitor-usa'
    scrape_interval: 15s
    static_configs:
    - targets: ['wis2node-monitor-usa:8111']

  - job_name: 'wis2node-monitor-france'
    scrape_interval: 15s
    static_configs:
    - targets: ['wis2node-monitor-france:8111']

  - job_name: 'wis2node-monitor-brazil'
    scrape_interval: 15s
    static_configs:
    - targets: ['wis2node-monitor-brazil:8111']

  - job_name: 'wis2node-monitor-china'
    scrape_interval: 15s
    static_configs:
    - targets: ['wis2node-monitor-china:8111']

#  provide remote target url and credentials
#remote_write:
# - url: <PROM_REMOTE_PUSH_URL>
#    basic_auth:
#      username: <PROM_REMOTE_USERNAME>
#      password: <PROM_REMOTE_PASSWORD>